# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: mulhamna.jirac
PackageVersion: 0.24.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: jirac-windows-x86_64.exe
    PortableCommandAlias: jirac
ReleaseDate: 2026-04-29
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mulhamna/jira-commands/releases/download/v0.24.2/jirac-windows-x86_64.zip
    InstallerSha256: eb4d316a81c792e4061aac2cd74ba8ae480d5541896a2d8216508415e70666e7
ManifestType: installer
ManifestVersion: 1.9.0
