# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: mulhamna.jirac
PackageVersion: 0.24.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: jirac-windows-x86_64.exe
    PortableCommandAlias: jirac
ReleaseDate: 2026-04-29
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mulhamna/jira-commands/releases/download/v0.24.1/jirac-windows-x86_64.zip
    InstallerSha256: d74f5fc2cc94bda856a3e75a83c0ccf0fa18d0bd909e74e37ac5d9a430217cc6
ManifestType: installer
ManifestVersion: 1.9.0
