# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: mulhamna.jirac
PackageVersion: 0.16.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: jirac.exe
    PortableCommandAlias: jirac
ReleaseDate: 2026-04-24
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mulhamna/jira-commands/releases/download/v0.16.1/jirac-windows-x86_64.zip
    InstallerSha256: 570e0436c43daebf3746d01e8b5426b8318270be077ffbaf2d4e9821c0df8c1b
ManifestType: installer
ManifestVersion: 1.9.0
