# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: mulhamna.jirac
PackageVersion: 0.34.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: jirac-windows-x86_64.exe
    PortableCommandAlias: jirac
ReleaseDate: 2026-05-07
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mulhamna/jira-commands/releases/download/v0.34.0/jirac-windows-x86_64.zip
    InstallerSha256: 15cd98c3b9bf49eb8f7e59fd7f739653ed1cb46f6232c993714cf47bc97a50d9
ManifestType: installer
ManifestVersion: 1.9.0
