# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: mulhamna.jirac
PackageVersion: 0.24.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: jirac-windows-x86_64.exe
    PortableCommandAlias: jirac
ReleaseDate: 2026-04-29
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mulhamna/jira-commands/releases/download/v0.24.3/jirac-windows-x86_64.zip
    InstallerSha256: f9f2d7be1785a6027c35afe3814bf3dc2e6d859c87ba4c8e1a9dd18784c2b4e2
ManifestType: installer
ManifestVersion: 1.9.0
